### ISSUE TITLE
[question] How to choose a preset in registration module

### ISSUE THREAD

**Issue by upupming** [lassoan/SlicerSegmentationRecipes#3]
Thanks for your great material about segmentation on 3D Slicer, this helps a lot. 

However, when I am reading this doc: https://github.com/lassoan/SlicerSegmentationRecipes/blob/040fc5a954f89d900f172c3ab504743ecfba7145/VesselSegmentationBySubtraction/README.md , I cannot proceed as it says.

First, I cannot find a module named `General registration (Elastix)`, but there is a very similar one named `General registration (BRAINS)`. However, when I use the `... BRAINS`  module, I cannot find the Preset settings as the doc says:

> For `Preset` choose `generic (all)`

And when I click the apply button, it report an error:

```bash
General Registration (BRAINS) standard error:

ERROR: No registration phases specified to perform!
```

![image](https://user-images.githubusercontent.com/24741764/130034302-5865bbdb-27ed-42b7-b803-f815f96a6e55.png)

Could you please help me to fix this problem, thanks in advance?

**Comment by lassoan** [comment]
You need to install SlicerElastix extension - see [prerequisites](https://github.com/lassoan/SlicerSegmentationRecipes/blob/040fc5a954f89d900f172c3ab504743ecfba7145/VesselSegmentationBySubtraction/README.md#prerequisites).
