### ISSUE TITLE
VesselSegmentationBySubtraction samples links return 404

### ISSUE THREAD

**Issue by test123-23-7** [lassoan/SlicerSegmentationRecipes#4]
The [CTABrainBaseline](http://slicer.kitware.com/midas3/download/item/453299/CTABrainBaseline.nrrd) and [CTABrainContrast.nrrd](http://slicer.kitware.com/midas3/download/item/453309/CTABrainContrast.nrrd) links for this turorial: (https://lassoan.github.io/SlicerSegmentationRecipes/VesselSegmentationBySubtraction/) return "Not Found".

**Comment by lassoan** [comment]
Thanks for reporting, the links broke due to a server migration. I've updated the links now.
